name: xeus-cling
channels:
  - conda-forge
dependencies:
  - xeus-cling=0.8.1
  - xtensor=0.21.2
  - xtensor-blas=0.17.1
  - matplotlib
  - sympy
  - heapdict
  - python-graphviz
  - octave_kernel
  - notebook
